### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by 6a6ak**
border-radius: 25px;

### CODE REVIEW

**Comment by timotheeMM** [comment]
Hello @6a6ak, thank you very much for your pull request !
You’re the first person to contribute to one of my projects. :blush:

**Comment by 6a6ak** [comment]
Same here 🤣

**Comment by timotheeMM** [comment]
:laughing:
I added your GitHub username  "@6a6ak"  in the CONTRIBUTORS.md file.

**Comment by 6a6ak** [comment]
Send me a message in private we can plan for a good repo 😉

**Pull request merged**
